apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: {{ .Release.Namespace }}
type: Opaque
data:
    mysql-root-username: cm9vdA==  #root int encoded widh 64
    mysql-root-password: cm9vdA==
