apiVersion: v1
kind: Service
metadata:
  name: empapp-front-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: empapp-front
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      