apiVersion: apps/v1
kind: Deployment
metadata:
  name: empapp-back
  labels:
    app: empapp-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empapp-back
  template:
    metadata:
      labels:
        app: empapp-back
    spec:
      containers:
      - name: empapp-back
        image: khalil4/employee-app-back
      
        ports:
        - containerPort: 80
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: database_url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password  
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update

                 
---
apiVersion: v1
kind: Service
metadata:
  name: empapp-back-service
spec:
  selector:
    app: blog-back
  type: ClusterIP  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
