apiVersion: apps/v1
kind: Deployment
metadata:
  name: empapp-front
  labels:
    app: empapp-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: empapp-front
  template:
    metadata:
      labels:
        app: empapp-front
    spec:
      containers:
      - name: empapp-front
        image: khalil4/blogfront:V1
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: backend-configmap
              key: api_url
        
         
             
                 
---
apiVersion: v1
kind: Service
metadata:
  name: empapp-front-service
spec:
  selector:
    app: empapp-front
  type: nodePort  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007