apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: {{ .Release.Namespace }}
data:
  database_url: jdbc:mysql://mysql.default:3306/employeemanager
  database_name: employeemanager