apiVersion: v1
kind: Service
metadata:
  name: empapp-back-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: empapp-back
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
